- name: Deploy Hexo
        env:
          ACTION_DEPLOY_KEY: ${{ secrets.HEXO_DEPLOY_PRI }}
        run: |
          mkdir -p ~/.ssh/
          echo "$ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          # 这一行是新加的：告诉 SSH 允许使用较旧的算法（解决 libcrypto 报错）
          echo "PubkeyAcceptedKeyTypes +ssh-rsa" >> ~/.ssh/config
          git config --global user.name "1TRhez"
          git config --global user.email "saa.1trhez@gmail.com"
          hexo clean
          hexo generate
          hexo deploy